# Copyright 2022 Yahoo Inc.
# Licensed under the terms of the Apache License 2.0. Please see LICENSE file in project root for terms.

name: license check
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read


jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.19.4

      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install addlicense
        run: go install github.com/google/addlicense@latest

      - name: Check license headers
        run: |
          set -e
          addlicense -l apache -c 'Yahoo,' -ignore "third_party/**" -v *
          git diff --exit-code
